services:
  mongo:
    image: mongo:7
    container_name: saas_boilerplate_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: saas_boilerplate_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: saas_boilerplate_azurite
    restart: unless-stopped
    command: azurite --blobHost 0.0.0.0 --blobPort 10000
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data

volumes:
  mongo_data:
  azurite_data:
