import { Types } from 'mongoose';
import { AuditLogModel, OrganisationModel, RoleModel, SecurityEventModel, UserModel } from '../models/index.js';
import { hashPassword } from '../utils/password.js';

export interface TestTenantOptions {
  name?: string;
  slug?: string;
  domain?: string;
  email?: string;
  password?: string;
  permissions?: string[];
}

let tenantCounter = 0;

export async function createTestTenant(options: TestTenantOptions = {}) {
  tenantCounter += 1;
  const suffix = `${tenantCounter}-${new Types.ObjectId().toString().slice(-6)}`;
  const domain = options.domain ?? `tenant-${suffix}.example.com`;
  const organisation = await OrganisationModel.create({
    name: options.name ?? `Test Organisation ${suffix}`,
    slug: options.slug ?? `test-organisation-${suffix}`,
    status: 'active',
    domains: [{ domain, verified: true, is_primary: true }],
    auth_config: {
      login_method: 'native',
      sso_enabled: false,
      provider: null,
      allowed_email_domains: [],
      enforce_sso: false,
      enforce_mfa: false
    }
  });

  const role = await RoleModel.create({
    organisation_id: organisation._id,
    name: options.permissions?.includes('platform.organisations.view') ? 'Platform Test Admin' : 'Organisation Test Admin',
    description: 'Test role generated by v0.16.0 test helpers',
    is_system_role: true,
    permission_keys: options.permissions ?? []
  });

  const password = options.password ?? 'ChangeMe123!';
  const email = (options.email ?? `admin-${suffix}@example.com`).toLowerCase();
  const user = await UserModel.create({
    organisation_id: organisation._id,
    email,
    email_normalised: email,
    first_name: 'Test',
    last_name: 'Admin',
    display_name: 'Test Admin',
    status: 'active',
    auth: {
      auth_type: 'native',
      password_hash: hashPassword(password),
      mfa_enabled: false,
      mfa_status: 'not_required',
      mfa_provider: 'none',
      last_mfa_at: null,
      last_login_at: null
    },
    role_ids: [role._id],
    profile: { timezone: 'UTC' }
  });

  return { organisation, role, user, email, password };
}

export async function createAuditLogForTenant(organisationId: Types.ObjectId, action = 'test.audit.event') {
  return AuditLogModel.create({
    organisation_id: organisationId,
    action,
    resource_type: 'test_resource',
    resource_id: new Types.ObjectId().toString(),
    details: { source: 'v0.16.0 tests' },
    ip_address: '127.0.0.1',
    user_agent: 'vitest'
  });
}

export async function createSecurityEventForTenant(
  organisationId: Types.ObjectId,
  eventType = 'test.security.event',
  severity: 'low' | 'medium' | 'high' | 'critical' = 'low',
  status: 'success' | 'failure' | 'warning' | 'blocked' | 'info' = 'success'
) {
  return SecurityEventModel.create({
    organisation_id: organisationId,
    event_type: eventType,
    severity,
    status,
    resource_type: 'test_resource',
    resource_id: new Types.ObjectId().toString(),
    details: { source: 'v0.16.0 tests' },
    ip_address: '127.0.0.1',
    user_agent: 'vitest'
  });
}
