import { Router } from 'express';
import { healthRouter } from '../modules/health/health.routes.js';
import { schemaRouter } from '../modules/schema/schema.routes.js';
import { organisationRouter } from '../modules/organisations/organisation.routes.js';
import { userRouter } from '../modules/users/user.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';
import { oidcAuthRouter } from '../modules/auth/oidc.routes.js';
import { permissionRouter } from '../modules/permissions/permission.routes.js';
import { roleRouter } from '../modules/roles/role.routes.js';
import { personalAccessTokenRouter } from '../modules/personalAccessTokens/personalAccessToken.routes.js';
import { organisationApiTokenRouter } from '../modules/organisationApiTokens/organisationApiToken.routes.js';
import { externalRouter } from '../modules/external/external.routes.js';
import { publicOrganisationLoginRouter } from '../modules/public/publicOrganisationLogin.routes.js';
import { publicOrganisationThemeRouter } from '../modules/public/publicOrganisationTheme.routes.js';
import { publicOrganisationAuthOptionsRouter } from '../modules/public/publicOrganisationAuthOptions.routes.js';
import { organisationBrandingRouter } from '../modules/organisationBranding/organisationBranding.routes.js';
import { organisationAuthConfigRouter } from '../modules/organisationAuthConfig/organisationAuthConfig.routes.js';
import { organisationMfaPolicyRouter } from '../modules/organisationMfaPolicy/organisationMfaPolicy.routes.js';
import { publicOrganisationMfaPolicyRouter } from '../modules/public/publicOrganisationMfaPolicy.routes.js';
import { organisationSsoConfigRouter } from '../modules/organisationSsoConfig/organisationSsoConfig.routes.js';
import { publicOrganisationSsoOptionsRouter } from '../modules/public/publicOrganisationSsoOptions.routes.js';
import { featureCatalogueRouter, organisationFeatureRouter } from '../modules/features/feature.routes.js';
import { planCatalogueRouter, organisationPlanRouter, platformOrganisationPlanRouter } from '../modules/plans/plan.routes.js';
import { fileRouter } from '../modules/files/file.routes.js';
import { organisationAuditLogRouter, platformAuditLogRouter, platformOrganisationAuditLogRouter } from '../modules/auditLogs/auditLog.routes.js';
import { organisationSecurityEventRouter, platformSecurityEventRouter, platformOrganisationSecurityEventRouter } from '../modules/securityEvents/securityEvent.routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/public/organisation-login', publicOrganisationLoginRouter);
apiRouter.use('/public', publicOrganisationThemeRouter);
apiRouter.use('/public', publicOrganisationAuthOptionsRouter);
apiRouter.use('/public', publicOrganisationMfaPolicyRouter);
apiRouter.use('/public', publicOrganisationSsoOptionsRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/auth', oidcAuthRouter);
apiRouter.use('/permissions', permissionRouter);
apiRouter.use('/internal/schema', schemaRouter);
apiRouter.use('/platform/audit-logs', platformAuditLogRouter);
apiRouter.use('/platform/security-events', platformSecurityEventRouter);
apiRouter.use('/platform/organisations/:organisationId/audit-logs', platformOrganisationAuditLogRouter);
apiRouter.use('/platform/organisations/:organisationId/security-events', platformOrganisationSecurityEventRouter);
apiRouter.use('/platform/organisations', organisationRouter);
apiRouter.use('/platform/organisations/:organisationId/users', userRouter);
apiRouter.use('/org/roles', roleRouter);
apiRouter.use('/org/branding', organisationBrandingRouter);
apiRouter.use('/org/auth-config', organisationAuthConfigRouter);
apiRouter.use('/org/mfa-policy', organisationMfaPolicyRouter);
apiRouter.use('/org/sso-config', organisationSsoConfigRouter);
apiRouter.use('/features', featureCatalogueRouter);
apiRouter.use('/org/features', organisationFeatureRouter);
apiRouter.use('/platform/plans', planCatalogueRouter);
apiRouter.use('/org/plan', organisationPlanRouter);
apiRouter.use('/platform/organisations/:organisationId/plan', platformOrganisationPlanRouter);
apiRouter.use('/org/files', fileRouter);
apiRouter.use('/org/audit-logs', organisationAuditLogRouter);
apiRouter.use('/org/security-events', organisationSecurityEventRouter);
apiRouter.use('/org/personal-access-tokens', personalAccessTokenRouter);
apiRouter.use('/org/api-tokens', organisationApiTokenRouter);
apiRouter.use('/external', externalRouter);
